// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gznamibzhawprsdhqoaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6bmFtaWJ6aGF3cHJzZGhxb2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NzM2OTcsImV4cCI6MjA2NTM0OTY5N30.Myjc0K7zscD-AVmB1qqEWRS10f3KoW6Q9QTxfCMQlW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);